name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack install

      - name: Install dependencies
        run: pnpm install

      - name: Run CI
        run: pnpm run ci

      - name: Build pages
        run: pnpm run --filter */picker build-pages

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/picker/pages/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: ci
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
